package com.akxy.mapper;

import com.akxy.entity.TB1;

public interface TB1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_1
     *
     * @mbggenerated Thu Mar 07 15:37:11 CST 2019
     */
    int insert(TB1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_1
     *
     * @mbggenerated Thu Mar 07 15:37:11 CST 2019
     */
    int insertSelective(TB1 record);
}