package com.akxy.entity;

/**
 * @author wangp
 */
public class MineKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MINE.MINECODE
     *
     * @mbggenerated Fri Mar 08 09:12:26 CST 2019
     */
    private String minecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MINE.MINENAME
     *
     * @mbggenerated Fri Mar 08 09:12:26 CST 2019
     */
    private String minename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MINE.MINECODE
     *
     * @return the value of MINE.MINECODE
     *
     * @mbggenerated Fri Mar 08 09:12:26 CST 2019
     */
    public String getMinecode() {
        return minecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MINE.MINECODE
     *
     * @param minecode the value for MINE.MINECODE
     *
     * @mbggenerated Fri Mar 08 09:12:26 CST 2019
     */
    public void setMinecode(String minecode) {
        this.minecode = minecode == null ? null : minecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MINE.MINENAME
     *
     * @return the value of MINE.MINENAME
     *
     * @mbggenerated Fri Mar 08 09:12:26 CST 2019
     */
    public String getMinename() {
        return minename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MINE.MINENAME
     *
     * @param minename the value for MINE.MINENAME
     *
     * @mbggenerated Fri Mar 08 09:12:26 CST 2019
     */
    public void setMinename(String minename) {
        this.minename = minename == null ? null : minename.trim();
    }
}