SELECT 'JIER' AS NAME,MAX(COLLECT_TIME) FROM JIER.POSRESULT UNION
SELECT 'ANJU' AS NAME,MAX(COLLECT_TIME) FROM ANJU.POSRESULT UNION
SELECT 'PANXI' AS NAME,MAX(COLLECT_TIME) FROM PANXI.POSRESULT UNION
SELECT 'YUNHE' AS NAME,MAX(COLLECT_TIME) FROM YUNHE.POSRESULT UNION
SELECT 'JISAN' AS NAME,MAX(COLLECT_TIME) FROM JISAN.POSRESULT UNION
SELECT 'XINHE' AS NAME,MAX(COLLECT_TIME) FROM XINHE.POSRESULT UNION
SELECT 'YINENG' AS NAME,MAX(COLLECT_TIME) FROM YINENG.POSRESULT UNION
SELECT 'GUOTUN' AS NAME,MAX(COLLECT_TIME) FROM GUOTUN.POSRESULT UNION
SELECT 'DAXING' AS NAME,MAX(COLLECT_TIME) FROM DAXING.POSRESULT UNION
SELECT 'NANTUN' AS NAME,MAX(COLLECT_TIME) FROM NANTUN.POSRESULT UNION
SELECT 'YIQIAO' AS NAME,MAX(COLLECT_TIME) FROM YIQIAO.POSRESULT UNION
SELECT 'SUNCUN' AS NAME,MAX(COLLECT_TIME) FROM SUNCUN.POSRESULT UNION
SELECT 'DONGTAN' AS NAME,MAX(COLLECT_TIME) FROM DONGTAN.POSRESULT UNION
SELECT 'TANGKOU' AS NAME,MAX(COLLECT_TIME) FROM TANGKOU.POSRESULT UNION
SELECT 'BAODIAN' AS NAME,MAX(COLLECT_TIME) FROM BAODIAN.POSRESULT UNION
SELECT 'XINGCUN' AS NAME,MAX(COLLECT_TIME) FROM XINGCUN.POSRESULT UNION
SELECT 'GUCHENG' AS NAME,MAX(COLLECT_TIME) FROM GUCHENG.POSRESULT UNION
SELECT 'WANGLOU' AS NAME,MAX(COLLECT_TIME) FROM WANGLOU.POSRESULT UNION
SELECT 'HUAFENG' AS NAME,MAX(COLLECT_TIME) FROM HUAFENG.POSRESULT UNION
SELECT 'HUAHENG' AS NAME,MAX(COLLECT_TIME) FROM HUAHENG.POSRESULT UNION
SELECT 'ZHAOLOU' AS NAME,MAX(COLLECT_TIME) FROM ZHAOLOU.POSRESULT UNION
SELECT 'JINYUAN' AS NAME,MAX(COLLECT_TIME) FROM JINYUAN.POSRESULT UNION
SELECT 'XIAOYUN' AS NAME,MAX(COLLECT_TIME) FROM XIAOYUN.POSRESULT UNION
SELECT 'YUNCHENG' AS NAME,MAX(COLLECT_TIME) FROM YUNCHENG.POSRESULT UNION
SELECT 'TIANCHEN' AS NAME,MAX(COLLECT_TIME) FROM TIANCHEN.POSRESULT UNION
SELECT 'SHUANGHE' AS NAME,MAX(COLLECT_TIME) FROM SHUANGHE.POSRESULT UNION
SELECT 'TANGYANG' AS NAME,MAX(COLLECT_TIME) FROM TANGYANG.POSRESULT UNION
SELECT 'SHANXIAN' AS NAME,MAX(COLLECT_TIME) FROM SHANXIAN.POSRESULT UNION
SELECT 'XINJULONG' AS NAME,MAX(COLLECT_TIME) FROM XINJULONG.POSRESULT UNION
SELECT 'XIEZHUANG' AS NAME,MAX(COLLECT_TIME) FROM XIEZHUANG.POSRESULT UNION
SELECT 'GAOZHUANG' AS NAME,MAX(COLLECT_TIME) FROM GAOZHUANG.POSRESULT UNION
SELECT 'JINZHUANG' AS NAME,MAX(COLLECT_TIME) FROM JINZHUANG.POSRESULT UNION
SELECT 'YANGCHENG' AS NAME,MAX(COLLECT_TIME) FROM YANGCHENG.POSRESULT UNION
SELECT 'LIANGBAOSI' AS NAME,MAX(COLLECT_TIME) FROM LIANGBAOSI.POSRESULT UNION
SELECT 'PENGZHUANG' AS NAME,MAX(COLLECT_TIME) FROM PENGZHUANG.POSRESULT UNION
SELECT 'LIANGZHUANG' AS NAME,MAX(COLLECT_TIME) FROM LIANGZHUANG.POSRESULT UNION
SELECT 'FENGYUANSHIYE' AS NAME,MAX(COLLECT_TIME) FROM FENGYUANSHIYE.POSRESULT UNION
SELECT 'QIWUSHENGJIAN' AS NAME,MAX(COLLECT_TIME) FROM QIWUSHENGJIAN.POSRESULT UNION
SELECT 'XINGLONGZHUANG' AS NAME,MAX(COLLECT_TIME) FROM XINGLONGZHUANG.POSRESULT UNION
SELECT 'TENGDONGSHENGJIAN' AS NAME,MAX(COLLECT_TIME) FROM TENGDONGSHENGJIAN.POSRESULT;

# 删除微震数据库错误的数据
DELETE FROM JIER.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM JIER.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM ANJU.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM ANJU.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM PANXI.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM PANXI.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM YUNHE.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM YUNHE.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM JISAN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM JISAN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM XINHE.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM XINHE.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM YINENG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM YINENG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM GUOTUN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM GUOTUN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM DAXING.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM DAXING.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM NANTUN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM NANTUN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM YIQIAO.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM YIQIAO.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM SUNCUN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM SUNCUN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM DONGTAN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM DONGTAN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM TANGKOU.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM TANGKOU.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM BAODIAN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM BAODIAN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM XINGCUN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM XINGCUN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM GUCHENG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM GUCHENG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM WANGLOU.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM WANGLOU.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM HUAFENG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM HUAFENG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM HUAHENG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM HUAHENG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM ZHAOLOU.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM ZHAOLOU.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM JINYUAN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM JINYUAN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM XIAOYUN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM XIAOYUN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM YUNCHENG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM YUNCHENG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM TIANCHEN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM TIANCHEN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM SHUANGHE.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM SHUANGHE.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM TANGYANG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM TANGYANG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM SHANXIAN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM SHANXIAN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM XINJULONG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM XINJULONG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM XIEZHUANG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM XIEZHUANG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM GAOZHUANG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM GAOZHUANG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM JINZHUANG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM JINZHUANG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM YANGCHENG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM YANGCHENG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM LIANGBAOSI.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM LIANGBAOSI.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM PENGZHUANG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM PENGZHUANG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM LIANGZHUANG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM LIANGZHUANG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM FENGYUANSHIYE.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM FENGYUANSHIYE.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM QIWUSHENGJIAN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM QIWUSHENGJIAN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM XINGLONGZHUANG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM XINGLONGZHUANG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
DELETE FROM TENGDONGSHENGJIAN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM TENGDONGSHENGJIAN.AREA)AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');



SELECT COUNT(*) , 'JIER' AS NAME FROM JIER.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM JIER.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'ANJU' AS NAME FROM ANJU.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM ANJU.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'PANXI' AS NAME FROM PANXI.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM PANXI.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'YUNHE' AS NAME FROM YUNHE.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM YUNHE.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'JISAN' AS NAME FROM JISAN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM JISAN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'XINHE' AS NAME FROM XINHE.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM XINHE.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'YINENG' AS NAME FROM YINENG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM YINENG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'GUOTUN' AS NAME FROM GUOTUN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM GUOTUN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'DAXING' AS NAME FROM DAXING.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM DAXING.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'NANTUN' AS NAME FROM NANTUN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM NANTUN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'YIQIAO' AS NAME FROM YIQIAO.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM YIQIAO.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'SUNCUN' AS NAME FROM SUNCUN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM SUNCUN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'DONGTAN' AS NAME FROM DONGTAN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM DONGTAN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'TANGKOU' AS NAME FROM TANGKOU.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM TANGKOU.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'BAODIAN' AS NAME FROM BAODIAN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM BAODIAN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'XINGCUN' AS NAME FROM XINGCUN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM XINGCUN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'GUCHENG' AS NAME FROM GUCHENG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM GUCHENG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'WANGLOU' AS NAME FROM WANGLOU.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM WANGLOU.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'HUAFENG' AS NAME FROM HUAFENG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM HUAFENG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'HUAHENG' AS NAME FROM HUAHENG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM HUAHENG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'ZHAOLOU' AS NAME FROM ZHAOLOU.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM ZHAOLOU.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'JINYUAN' AS NAME FROM JINYUAN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM JINYUAN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'XIAOYUN' AS NAME FROM XIAOYUN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM XIAOYUN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'YUNCHENG' AS NAME FROM YUNCHENG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM YUNCHENG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'TIANCHEN' AS NAME FROM TIANCHEN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM TIANCHEN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'SHUANGHE' AS NAME FROM SHUANGHE.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM SHUANGHE.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'TANGYANG' AS NAME FROM TANGYANG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM TANGYANG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'SHANXIAN' AS NAME FROM SHANXIAN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM SHANXIAN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'XINJULONG' AS NAME FROM XINJULONG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM XINJULONG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'XIEZHUANG' AS NAME FROM XIEZHUANG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM XIEZHUANG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'GAOZHUANG' AS NAME FROM GAOZHUANG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM GAOZHUANG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'JINZHUANG' AS NAME FROM JINZHUANG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM JINZHUANG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'YANGCHENG' AS NAME FROM YANGCHENG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM YANGCHENG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'LIANGBAOSI' AS NAME FROM LIANGBAOSI.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM LIANGBAOSI.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'PENGZHUANG' AS NAME FROM PENGZHUANG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM PENGZHUANG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'LIANGZHUANG' AS NAME FROM LIANGZHUANG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM LIANGZHUANG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'FENGYUANSHIYE' AS NAME FROM FENGYUANSHIYE.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM FENGYUANSHIYE.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'QIWUSHENGJIAN' AS NAME FROM QIWUSHENGJIAN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM QIWUSHENGJIAN.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'XINGLONGZHUANG' AS NAME FROM XINGLONGZHUANG.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM XINGLONGZHUANG.AREA) AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss') union
SELECT COUNT(*) , 'TENGDONGSHENGJIAN' AS NAME FROM TENGDONGSHENGJIAN.POSRESULT WHERE AREA_ID  NOT IN (SELECT ID FROM TENGDONGSHENGJIAN.AREA)AND COLLECT_TIME > to_date('2019-02-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss');
